export const GET_PROFILE = 'GET_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const GET_CURRENT_PROFILE = 'GET_CURRENT_PROFILE';
export const CREATE_PROFILE = 'CREATE_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';